<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="cuiyishuodeMacBook-Pro.local" ignored="0" name="api测试用例" tests="7" failures="4" timestamp="17 八月 2020 04:19:59 GMT" time="5.118" errors="0">
  <testcase name="loginTrue" time="1.855" classname="com.wanmen.cases.users.LoginTest">
    <failure type="java.lang.AssertionError" message="找不到该属性:[id]">
      <![CDATA[java.lang.AssertionError: 找不到该属性:[id]
	at com.wanmen.util.JSONPathMi.eval(JSONPathMi.java:21)
	at com.wanmen.cases.users.LoginTest.loginTrue(LoginTest.java:49)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginTrue -->
  <testcase name="loginTrue" time="0.35" classname="com.wanmen.cases.users.LoginTest">
    <failure type="java.lang.AssertionError" message="找不到该属性:[id]">
      <![CDATA[java.lang.AssertionError: 找不到该属性:[id]
	at com.wanmen.util.JSONPathMi.eval(JSONPathMi.java:21)
	at com.wanmen.cases.users.LoginTest.loginTrue(LoginTest.java:49)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginTrue -->
  <testcase name="loginFalse" time="0.02" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="loginFalse" time="0.02" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="loginFalse" time="0.022" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="share" time="0.05" classname="com.wanmen.cases.users.FavoriteTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.wanmen.cases.Prepare.getAuthorization(Prepare.java:42)
	at com.wanmen.cases.users.FavoriteTest.getResult(FavoriteTest.java:67)
	at com.wanmen.cases.users.FavoriteTest.share(FavoriteTest.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- share -->
  <testcase name="share" time="0.454" classname="com.wanmen.cases.users.FavoriteTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.wanmen.cases.Prepare.getAuthorization(Prepare.java:42)
	at com.wanmen.cases.users.FavoriteTest.getResult(FavoriteTest.java:67)
	at com.wanmen.cases.users.FavoriteTest.share(FavoriteTest.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- share -->
</testsuite> <!-- api测试用例 -->
